application: family-recipe
version: 1
runtime: python
api_version: 1

handlers:
- url: /swf
  static_dir: swf

- url: /js
  static_dir: template/js

- url: /css
  static_dir: template/css
  
- url: /resource
  static_dir: template/resource

- url: .*
  script: main.py
